apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: andre
spec:
  project: default
  source:
    repoURL: https://github.com/Ainfosecsss/website.git 
    targetRevision: HEAD
    path: projects/argo/exam:wple-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
